### ISSUE TITLE
Disabled button is press-able when rendered with wrapper option

### ISSUE THREAD

**Issue by etaiklein** [callstack/react-native-testing-library#981] opened 2022-05-19 22:11 UTC
## Describe the bug

Disabled calls onPress on fireEvent.press when rendered with a wrapper, but does not rendered without a wrapper.

## Steps to Reproduce

`render(<Button {...props} disabled={true} />)` does not call onPress on fireEvent.press, but
`render(<Button {...props} disabled={true} />, { wrapper: ({ children }) => <>{children}</> })` calls onPress on fireEvent.press 

See sandbox:
https://codesandbox.io/s/laughing-butterfly-3txunr?file=/src/Button.test.js

## Screenshots

<img width="1861" alt="Screen Shot 2022-05-19 at 6 04 51 PM" src="https://user-images.githubusercontent.com/4458476/169412289-cbb8c40d-0433-4599-83e7-7d32be0ad68a.png">

## Versions

  npmPackages:
    @testing-library/react-native: 9.1.0 => 9.1.0
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-test-renderer: 17.0.1 => 17.0.1

**Comment by AugustinLF** [comment] 2022-09-04 14:41
That's very strange, when adding a test to our codebase to cover this use-case everything worked fine, even though I can see that things don't work as they should in your codesandbox.

```
test.only('should not fire on disabled Pressable with a render wrapper', () => {
  const onPress = jest.fn();
  const { getByText } = render(
    <Pressable onPress={onPress} disabled>
      <Text>Trigger</Text>
    </Pressable>,
    { wrapper: ({ children }) => <>{children}</> }
  );
  fireEvent.press(getByText('Trigger'));
  expect(onPress).toHaveBeenCalledTimes(0);
});
```

When adding your example in our `examples/basic` folder, it also works fine. So I'll assume the issue is somewhere with your setup?

I'll close the issue for now, if you can manage to reproduce with an easier with our setup, or if you can help pinpoint the problem, please let me know and I'll reopen.

**Closed by AugustinLF** 2022-09-04 14:41 UTC
