### ISSUE TITLE
Test fails due to Redux Persist migrate Option

### ISSUE THREAD

**Issue by szkieb** [callstack/react-native-testing-library#1519] opened 2023-11-03 12:17 UTC
## Describe the bug
Running tests while having the migrate option in my store's persistConfig active fails the test. 
Commenting out the migrate option  allows the test to run without failing. 

## Expected behavior

Tests should run without having to change my redux store setup. 
The docs on redux store should include information on redux persist test configs. 

## Steps to Reproduce

Create a redux store with the following persistConfig

```
const persistConfig = {
  key: 'root',
  storage: AsyncStorage,
  blacklist: [],
  version: 1,
  migrate: createMigrate(migrations, { debug: false }),
};
```

Setup the redux test environment according to the docs. 

Run the test to see the following error:
![image](https://github.com/callstack/react-native-testing-library/assets/102992385/2148c028-6ebf-4521-a92f-0fe0c67e8dad)

Comment out the migrate option in your persistConfig and run your test again to see that the error no longer appears. 

## Versions

  npmPackages:
    @testing-library/react-native: ^12.3.2 => 12.3.2 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-test-renderer: ^18.2.0 => 18.2.0

**Comment by pierrezimmermannbam** [comment] 2023-11-06 18:06
Hello @szkieb, thanks for submitting your issue! This does not look to be related to RNTL, it's an issue with the transpilation of your node modules. From what I see you get an error because the redux-persist package is not transpiled. I tried to reproduce the error but it works on my end. The difference I'm noticing is that it uses redux-persist/lib which is in commonjs and not redux-persist/es. Not sure why imports are not resolved correctly, this may have been fixed in an ulterior version of the lib, I have tried with version 6.0.0. If you can't upgrade you could force the resolution of the imports using the `moduleNameMapper` option in your jest config.

I hope this helps you, I'll close this issue because it's not related to RNTL but let me know if you have any further questions

**Closed by pierrezimmermannbam** 2023-11-06 18:06 UTC
