### ISSUE TITLE
Extreme test flakeyness 

### ISSUE THREAD

**Issue by mikefisher84** [callstack/react-native-testing-library#895] opened 2022-01-03 16:42 UTC
## Describe the bug

Hi all, we're upgrading our app from an old version of React Native Testing Library. Specifically it was an old fork called `daveols/native-testing-library#support-react-native-63-dist` that supported RN 63 which we needed support for at the time. 
Now we're upgrading to v9 of this library and are noticing lots of new issues. 

Our app has about 1700 unit tests and I'm noticing extreme flakeyness after installing v9. I've been skipping the flakey tests but right now I have about 175 skipped tests and counting. Almost every tests fails throwing this error: 
`TypeError: _reactNative.Animated.timing is not a function`

This is after carefully following the migration guide for each version in this repo. I'm not sure what could be happening here. 

## Expected behavior
I expect the tests to pass or fail consistently. 

## Steps to Reproduce

- Run the tests with jest 26
- randomly get `TypeError: _reactNative.Animated.timing is not a function` errors

## Screenshots

```
  TypeError: _reactNative.Animated.timing is not a function

      193 |               algoliaData: algoliaData ?? {},
      194 |               position: index,
    > 195 |               routeParams: route,
          |                           ^
      196 |               categoryParams,
      197 |             };
      198 |

      at collapse (src/components/ButtonUpdateQuantitySmall/index.tsx:195:27)
      at Timeout._onTimeout (src/components/ButtonUpdateQuantitySmall/index.tsx:224:15)
```

## Versions

```
"@testing-library/react-hooks": "^3.7.0",
"@testing-library/react-native": "9.0.0",
"@testing-library/jest-native": "4.0.4",
"jest": "^26.6.3",
"jest-circus": "^26.6.3",
"jest-expo": "^42.0.0",
```

  run following command in terminal of your root project and paste the result down

  `npx envinfo --npmPackages react,react-native,react-test-renderer,@testing-library/react-native`
```
  npmPackages:
    @testing-library/react-native: 9.0.0 => 9.0.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-test-renderer: 16.13.1 => 16.13.1
```

**Comment by coelhucas** [comment] 2022-02-24 14:34
Can you make a small environment where this is reproduced? I had this problem when not using `useFakeTimers` in places which depended of components that also use it. Wasn't a problem with the testing library but rather a PEBKAC.

**Comment by mdjastrzebski** [comment] 2022-06-02 10:16
Closing because of lack of recent activity.

**Closed by mdjastrzebski** 2022-06-02 10:16 UTC

**Comment by smikheiev** [comment] 2022-07-15 12:57
@mikefisher84 were you able to fix the issue?
