### ISSUE TITLE
Testing react-native-snap-carousel component

### ISSUE THREAD

**Issue by dev-andremonteiro** [callstack/react-native-testing-library#652] opened 2021-01-11 22:01 UTC
Hello,

I have been trying to test the `Carousel` component from `react-native-snap-carousel` and I keep on getting this error: `TypeError: Cannot read property 'width' of undefined`.  Searching around I couldn't find anything that helped me debug this, there's no mention of this issue in the react-native-snap-carousel repository too.

Here's a minimal example for you: 

```js
import React from 'react';
import { Text, View } from 'react-native';
import Carousel from 'react-native-snap-carousel';

const data = [
  { text: 'First', id: '1' },
  { text: 'Second', id: '2' }
];

export default function Andre() {
  const _renderItem = ({ item }: { item: any }) => {
    return (
      <View style={{ width: 610, height: 530, backgroundColor: 'red' }}>
        <Text>{item.text}</Text>
      </View>
    );
  };

  return (
    <View>
      <Carousel
        itemWidth={610}
        keyExtractor={item => `carousel_${item.id}`}
        data={data}
        sliderWidth={750}
        renderItem={_renderItem}
        testID="carousel"
      />
    </View>
  );
}
```

```js
import React from 'react';
import { fireEvent, render } from '@testing-library/react-native';
import Andre from '../Andre';

const eventData = {
  nativeEvent: {
    contentOffset: {
      y: 0,
      x: 610
    }
  },
  contentSize: {
    // Dimensions of the scrollable content
    height: 530,
    width: 1250
  },
  layoutMeasurement: {
    // Dimensions of the device
    height: 1334,
    width: 750
  }
};

describe('Testing Carousel', () => {
  test('Try to scroll', () => {
    const wraper = <Andre />;

    const { getByTestId } = render(wraper);

    expect(() => getByTestId('carousel')).not.toThrow();

    const Carousel = getByTestId('carousel');
    fireEvent.scroll(Carousel, eventData);
  });
});
```

I am using these libraries: 

    

>     Expo SDK 39
>     "react-test-renderer": "16.14.0"
>     "jest-expo": "~39.0.0",
>     "@testing-library/react-native": "^7.1.0",
>     "react-native-snap-carousel": "^3.9.1"

**Comment by tlands** [comment] 2021-11-20 01:26
`contentSize` and `layoutMeasurements` should be inside of the `nativeEvent` object:

`fireEvent.scroll(<YOUR QUERY HERE>), {
        nativeEvent: {
          contentOffset: {
            x: 200,
          },
          contentSize: { width: 200, height: 600 },
          layoutMeasurement: { width: 200, height: 600 },
        },
      });`

**Comment by mdjastrzebski** [comment] 2022-08-02 09:46
Closing issue as answered.

@dev-andremonteiro please report a new GH issue if the problem is present in the current version of RNTL (v11) in the recommended setup as in the [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic). If so, please provide also a minimal repro repository.

**Closed by mdjastrzebski** 2022-08-02 09:46 UTC
Labels: question
