### ISSUE TITLE
Strange behaviour when requesting elements via testID and regEx

### ISSUE THREAD

**Issue by hbel** [callstack/react-native-testing-library#800] opened 2021-08-24 08:06 UTC
## Describe the bug

In my code I use `getAllByTestId` with a regEx parameter to retrieve (I am aware that this is bad practice, but that's not the point here) some sub View components (with TestIDs of the form app.card.element_0 to app.card.element_5) from the component I am testing.

While `getAllByTestId(/./g)` always correctly returns everything that has a testID (including the above cards), explicitly requesting the cards with `getAllByTestId(/app\.card\.element_\d/g)` does not - it simply returns 2 of the above mentioned 5 cards. For other testable elements, these are returned in some cases, and in some cases they are not. 

## Expected behavior

I would expect getAllByTestId to return all elements with matching test ids correctly.

## Steps to Reproduce

Write a component with some sub components that are assigned test ids. Build a nested structure, e.g.

```
<ScrollView>
 <View><Text /></View>
 <View>
   <View>
  </View>
   <View>
  </View>
   <View>
  </View>
   <View>
  </View>
   <View>
  </View>
  </View>
</ScrollView>

```
## Versions

I am using react-native-testing-library 7.1.0 with react-native 0.63.4. Downgrading to 7.2.0 also did not help.

**Comment by thymikee** [comment] 2021-11-23 21:57
Maybe the problem is with the `g` flag maintaining some internal state? A repro that one could copy-paste would be helpful

**Comment by AugustinLF** [comment] 2022-03-29 10:03
Without a repro it'll be hard for us to figure out what's happening. I'll close the issue meanwhile but we'll reopen as soon as you provide us with more details.

**Closed by AugustinLF** 2022-03-29 10:03 UTC
