### ISSUE TITLE
onPress mock() does not get called

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [callstack/react-native-testing-library#1202] opened 2022-10-27 13:10 UTC
## Describe the bug
I want to mock `onPress` of a form component into my test component.

## Expected behavior
Working code
```
  it('Mock onPress', async () => {
    const onPressMock = jest.fn()
    render(
      <Button title='Submit' onPress={onPressMock} />
    )
    fireEvent.press(screen.getByText('Submit'))
    expect(onPressMock).toHaveBeenCalled()
  })
  ```

Failing code
```
const MockApp = ({ children }) => {
  return (
    <QueryClientProvider client={queryClient}>
      <NativeBaseProvider initialWindowMetrics={inset}>
        <ToastContextProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ToastContextProvider>
      </NativeBaseProvider>
    </QueryClientProvider>
  )
}

const EducationForm = ({
  defaultValues,
  educationId,
  navigation,
  testProp,
}: EducationFormProps) => {
  testProp = () => {
    console.log('Mock 1')
    return
  }
  return (
    <ScrollableView keyboardShouldPersistTaps='handled'>
      <Stack direction={'column'} p={3}>
        <Button label={'Submit'} color={'primary'} onPress={testProp} />
      </Stack>
    </ScrollableView>
  )
}
export default EducationForm

it('Mock onPress', async () => {
  const onPressMock = jest.fn()
  render(
    <MockApp>
      <NavigationContainer>
        <EducationForm defaultValues={{}} educationId='' testProp={onPressMock} />
      </NavigationContainer>
    </MockApp>
  )
  fireEvent.press(screen.getByText('Submit'))
  expect(onPressMock).toHaveBeenCalled()
})
```

## Screenshots

![image](https://user-images.githubusercontent.com/95462949/198293009-7cd9395e-3dcd-467d-a0ab-ad5dbae7cd54.png)

## Versions

![image](https://user-images.githubusercontent.com/95462949/198293171-15c49b76-9b86-4eba-bd63-3b47e2c2e672.png)

@AugustinLF Can you please help me on this

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 05:35
Anybody facing similar issues?

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 10:33
@thymikee Can you tell me where am I going wrong here

**Comment by pierrezimmermannbam** [comment] 2022-10-28 11:32
It's hard to tell what's not working based on the code you provided, does it work if you replace in the working example the button by the button you use in EducationForm ?

Mayve it's because in EducationForm you change the testProp value so I'd expect onPressMock not to have been called. Do you get the log though ?

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 11:59
@pierrezimmermannbam Thank you for looking into this
Working Example Button is from React Native

Not Working Example Button is from NativeBase, hence needs the wrapper.
Yes I get the log

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 12:04
@pierrezimmermannbam Replaced NativeBase Button with React Native Button into Failing code
Does not work

**Comment by pierrezimmermannbam** [comment] 2022-10-28 12:14
What if you delete those lines ? 

```tsx
testProp = () => {
    console.log('Mock 1')
    return
  }
```

testProp is correctly being called since you get a log, but onPressMock is not called because you override testProp I think

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 13:49
Currently `testProp` is doing some other job
I want to mock this from test case, hence checking this by log statement

**Comment by SupriyaPKalghatgi** [comment] 2022-10-28 14:27
@pierrezimmermannbam I commented out `testProp` and it works
But my requirement is that currently `testProp` is doing some other job, making API call
Whereas I want to mock this from test case to avoid making API call

**Comment by pierrezimmermannbam** [comment] 2022-10-28 14:59
I don't really understand your use case, if testProp is a jest.fn(), no api call will be made no ? But if you call something else than onPressMock then it's normal that your test fails if you expect onPressMock to have been called

**Comment by pierrezimmermannbam** [comment] 2022-10-28 15:00
To mock http i'd recommend using a dedicated library such as [nock](https://github.com/nock/nock) or [msw](https://github.com/mswjs/msw)

**Comment by SupriyaPKalghatgi** [comment] 2022-10-31 05:06
@pierrezimmermannbam I want `testProp` to return success status (assuming API returns success response)

**Comment by mdjastrzebski** [comment] 2022-10-31 09:34
@SupriyaPKalghatgi this looks like a setup issue with your test code. Pls provide a minimal reproduction repository so we can reproduce the error on our side, otherwise we cannot say much what is the issue here.

**Comment by SupriyaPKalghatgi** [comment] 2022-10-31 09:42
@mdjastrzebski The issue of calling `onPress` mock is resolved
Moving further, this is something that I want to achieve
https://github.com/callstack/react-native-testing-library/issues/1202#issuecomment-1296547810

**Comment by mdjastrzebski** [comment] 2022-10-31 10:23
@SupriyaPKalghatgi it seems like you are overwriting passed `testProp` param, hence it does not get called:

```
const EducationForm = ({
  defaultValues,
  educationId,
  navigation,
  testProp,
}: EducationFormProps) => {
  testProp = () => {
    console.log('Mock 1')
    return
  } // Here you overwrite the passed `testProp` param, causing the `jest.fn()` mock to be replaced by local arrow function.
```

**Comment by SupriyaPKalghatgi** [comment] 2022-10-31 10:45
@mdjastrzebski I have fixed that issue

**Comment by mdjastrzebski** [comment] 2022-10-31 10:52
@SupriyaPKalghatgi closing as there is no issue with RNTL itself. In case you need specific assistance in writing test code please use e.g. StackOverflow: https://stackoverflow.com/questions/tagged/react-native-testing-library

**Closed by mdjastrzebski** 2022-10-31 10:52 UTC
