### ISSUE TITLE
Why are accessibilty elements only text, textInput, and switch?

### ISSUE THREAD

**Issue by KrastanD** [callstack/react-native-testing-library#1566] opened 2024-02-22 17:24 UTC
## Ask your Question

I am using Tamagui and I want to check that a radio button has been checked but it's not able to and I think it's because Tamagui [adds the radio role to a view](https://github.com/tamagui/tamagui/blob/master/packages/radio-group/src/RadioGroup.tsx#L303) but React Native Testing Library only checks [text, textInput and switch elements for a role](https://github.com/callstack/react-native-testing-library/blob/main/src/helpers/accessiblity.ts#L99-L101).

Could you explain the reasoning for having only those elements as accessibility elements?
Do you have a recommended way that I can check that the radio button has been checked, or does Tamagui have to change how they set role?

**Comment by mdjastrzebski** [comment] 2024-02-22 19:56
To make a `View` an accessibility element just pass [`accessible={true}`](https://github.com/callstack/react-native-testing-library/blob/a670b2d4c1fb4df5326a63cb2852f4d6e37756da/src/helpers/accessiblity.ts#L93) props to it.


 The elements types you mention: `Text`, `TextInput` and `Switch` are considered to be accessible by default (even without `accessible={true}` prop).

**Comment by KrastanD** [comment] 2024-02-28 04:17
Adding `accessible` did make the element selectable, thank you!!! Idk how I missed that line. 

I created an [example expo app](https://github.com/KrastanD/rntl-tamagui-radio-example), but my test using userEvent wasn't checking the component. I tried all kinds of selectors but that didn't make a difference. Out of desperation I tried using fireEvent and that worked. Could you take a look? 

My hunch (from my understanding) is that fireEvent checks the parents handlers until it finds one, and userEvent doesn't do that so here, the onValueChange is on the RadioGroup level, not the RadioGroupItem so userEvent can't trigger it. I'm not sure how to trigger it with userEvent since I need to click on the specific item.

**Comment by tlmader** [comment] 2024-03-01 00:10
Just ran into this myself! I believe Tamagui should handle adding `accessible` to components, right? React Native Elements takes care of this for you.

**Comment by mdjastrzebski** [comment] 2024-04-26 20:24
@KrastanD I've reviewed this issue to check if it can be closed as it looked stale. I've run your repro repository and found it interesting. When I run `screen.debug()` on our failing test, it does not seems to contain `onPress` or similar event handler:

```
<View>
      <View
        __scopeRovingFocusGroup="RadioGroup"
        loop={true}
      >
        <View
          accessibilityRole="radiogroup"
        >
          <View>
            <View
              __scopeRovingFocusGroup="RadioGroup"
              accessibilityRole="radio"
              accessibilityState={
                {
                  "checked": false,
                }
              }
              accessible={true}
              active={false}
              focusable={true}
              id="radiogroup-1"
            />
            <View
              pointerEvents="none"
            />
            <Text
              htmlFor="radiogroup-1"
              id=":r3:"
              suppressHighlighting={true}
              userSelect="none"
            >
              First value
            </Text>
          </View>
          <View>
            <View
              __scopeRovingFocusGroup="RadioGroup"
              accessibilityRole="radio"
              accessibilityState={
                {
                  "checked": false,
                }
              }
              accessible={true}
              active={false}
              focusable={true}
              id="radiogroup-2"
            />
            <View
              pointerEvents="none"
            />
            <Text
              htmlFor="radiogroup-2"
              id=":r4:"
              suppressHighlighting={true}
              userSelect="none"
            >
              Second value
            </Text>
          </View>
          <View>
            <View
              __scopeRovingFocusGroup="RadioGroup"
              accessibilityRole="radio"
              accessibilityState={
                {
                  "checked": false,
                }
              }
              accessible={true}
              active={false}
              focusable={true}
              id="radiogroup-3"
            />
            <View
              pointerEvents="none"
            />
            <Text
              htmlFor="radiogroup-3"
              id=":r5:"
              suppressHighlighting={true}
              userSelect="none"
            >
              Third value
            </Text>
          </View>
        </View>
      </View>
    </View>
```

`screen.debug` displays only host views, and it seems that none of these views actually has any event handler 🧐 This will make `userEvent.press` fail as it expects `onPress` or `onPressIn`/`onPressOut` to be present. The reason why Fire Event works is that it invokes event handlers on both host and composite components, and Tamagui's RadioGroup seems to contain such [`onPress` handler](https://github.com/tamagui/tamagui/blob/f627d8296e6c798e81b32caf22323b70d0c7e002/packages/radio-group/src/RadioGroup.tsx#L318) on `RadioGroupItemFrame`.

**Comment by mfrfinbox** [comment] 2024-04-30 20:15
I am on the exact same situation, after hours of research I found that using the accesible attribute works fine and I'm thinking on adding a wrapper for all these elements from Tamagui that need it.

I wasn't very happy but I think that's the only solution, then I found that only fireEvent works instead of user event.

My concern is, can we rely on all these and be in peace with having the wrapper plus using fire event? It's messing with my head a little bit since I have the feeling that fireEvent will be away eventually, perhaps I'm wrong on that.

Thanks

**Comment by mdjastrzebski** [comment] 2024-05-01 16:17
@mfrfinbox you should raise this issue with Tamagui maintainers.  Their code is pretty complex due to abstractions and RN/web shared code, so they should be the best people to consult on this.

From my perspective the issue is on Tamagui's side (lack of `accessible` prop) but I would be happy to be proven wrong 😊

**Comment by KrastanD** [comment] 2024-05-01 16:35
For the accessible={true}, that should be contributed to tamagui directly imo so everyone gets it out the box and don't run into it like @mfrfinbox and I have. 

As for the host elements not showing onPress, I'm not quite sure how that happens. Aren't all composite elements built from host elements? The `RadioGroupItemFrame` has the onPress and extends a ThemableStack, which extends a YStack, which extends a View.

**Comment by mfrfinbox** [comment] 2024-05-01 17:57
I've open the issues on the Tamagui side, thanks

https://github.com/tamagui/tamagui/issues/2613
https://github.com/tamagui/tamagui/issues/2614

**Comment by mdjastrzebski** [comment] 2024-05-02 08:08
@mfrfinbox thank's for logging the issues, please update them with `MyComponent` source, as otherwise they are incomplete.

**Comment by mdjastrzebski** [comment] 2024-05-02 08:22
@KrastanD as for host elements, in React the components are not being extended (subclassed) in classic OOP way, they are being rendered (composed) by other (composite) components.
The [`YStack`](https://github.com/tamagui/tamagui/blob/f624c84baf4533af64b337ef99284e96a4a7d568/packages/stacks/src/Stacks.tsx#L49C9-L50C9) is a composite component that renders `View`, and should pass all it's props there as it uses `styled`, however for some reasons `onPress` from `RadioGroupItemFrame` does not get to the final `View` host element.

The reason why User Events insist on invoking only events on the host components, is that these are the only components that the user can see as they correspond to UI controls in iOS/Android. Composite components are just an abstraction, and cannot be directly observed or interacted by the users.

**Comment by mfrfinbox** [comment] 2024-05-02 08:58
> issues, p

Done!

**Comment by mdjastrzebski** [comment] 2024-05-23 11:42
Closing as it requires fixing upstream (Tamagui)

**Closed by mdjastrzebski** 2024-05-23 11:42 UTC
Labels: question
