### ISSUE TITLE
State not updating when hook modifies it

### ISSUE THREAD

**Issue by OlliePugh** [callstack/react-native-testing-library#1511] opened 2023-10-03 19:35 UTC
## Describe the bug

My hook returns a callback, this callback will then register an event listener. I am trying to test that when the method is called the internal state of the hook is modified. The state is modified in a event listener registered inside the hook. (hopefully my code explains it better than that 😆 )

I have captured the event listener so I can manually call it in my tests. I have validated that the `setRemoteStream` is called when I call the event handler, but `result.current.remoteStream` remains undefined. I can't understand why this isnt being updated alongside the state

## Expected behavior

I was expecting the `remoteStream` state to be updated with my `mockStream` value.

## Steps to Reproduce

My hook is as follows

```typescript
interface useJanusProps {
  url: string;
  streamId: number;
  connectionOptions: ConnectionOptions;
}

const useJanus = ({ url, connectionOptions, streamId }: useJanusProps) => {
  const [streamingPlugin, setStreamingPlugin] =
    useState<StreamingPlugin | null>();
  const [remoteStream, setRemoteStream] = useState<MediaStream | null>();
  const janus = useMemo<JanusClient>(
    () =>
      new JanusClient(
        url,
        connectionOptions,
        new MediaDevicesReactNativeShim(),
        new WebRTCReactNativeShim()
      ),
    [url, connectionOptions]
  );

  useEffect(() => {
    return stop;
  }, []);

  const watch = useCallback(async () => {
    if (remoteStream?.active) {
      console.error("watch called - stream already active");
    }
    const clientId = uuid.v4().toString();
    const connection = await janus.createConnection(clientId);
    const session = (await connection.createSession()) as Session;
    const streamingPlugin = (await session.attachPlugin(
      StreamingPlugin.NAME
    )) as StreamingPlugin;
    setStreamingPlugin(streamingPlugin);

    streamingPlugin.on("pc:track:remote", (trackEvent: RTCTrackEvent) => {
      if (remoteStream == null) {
        setRemoteStream(trackEvent.streams[0]);
      }
    });
    
    const { jsep } = await streamingPlugin.watch(streamId, null, null);
    await streamingPlugin.start(jsep);
  }, [janus, streamId, remoteStream]);

  const stop = useCallback(() => {
    remoteStream?.getTracks().forEach((track) => track.stop());
    streamingPlugin?.stop();
    setRemoteStream(null);
  }, [remoteStream, streamingPlugin]);

  return { watch, remoteStream, stop };
};
```

and my test is:
```typescript
describe("useJanus", () => {
  const mockClient = instantiateClassMock(Client);
  (Client as jest.Mock).mockReturnValue(mockClient);
  const mockConnection = instantiateClassMock(Connection);
  const mockSession = instantiateClassMock(Session);
  const mockStreamingPlugin = instantiateClassMock(StreamingPlugin);

  mockClient.createConnection.mockResolvedValue(mockConnection);
  mockConnection.createSession.mockResolvedValue(mockSession);
  mockSession.attachPlugin.mockResolvedValue(mockStreamingPlugin);
  mockStreamingPlugin.watch.mockResolvedValue({ jsep: "wibble" });
  
  it("should call the watch function and set remoteStream when called", async () => {
    const mockTrack = jest.fn();

    const { result, rerender } = renderHook(() =>
      useJanus({
        url: "ws://example.com/janus",
        connectionOptions: { keepalive: true },
        streamId: 123,
      })
    );

    await act(async () => {
      await result.current.watch();

      expect(mockStreamingPlugin.on).toHaveBeenCalledWith( // <-- this expect passes so the method is being registered
        "pc:track:remote",
        expect.any(Function)
      );
      mockStreamingPlugin.on.mock.calls;
      const onMethod = mockStreamingPlugin.on.mock.calls[0][1];

      onMethod({ streams: [mockTrack] });
    });

    rerender(null);

    await waitFor(() => {
      expect(result.current.remoteStream).toBe(mockTrack); // <--- this is always null
    });
  });
});
```

I do think there may be an issue with my implementation of the hook (as the testing for this feels overly-complicated), which I am very open to feedback to make that better also.

## Versions

npmPackages:
    @testing-library/react-native: ^12.3.0 => 12.3.0
    react: 18.2.0 => 18.2.0
    react-native: 0.72.5 => 0.72.5
    react-test-renderer: 18.2.0 => 18.2.0

**Comment by pierrezimmermannbam** [comment] 2023-10-10 19:06
Hi @OlliePugh ! It's kind of hard to tell what could be the issue here, have you tried debugging that test? I would specifically look at these two points:

- does the call to `onMethod` do something? If you add a log in your code in the callback passed to `streamingPlugin.on` do you see it?
- does the state `remoteStream ` ever changes and is reset to null for whatever reason or does it stay null at all time?

Regarding the way that this is tested, the test is indeed quite complicated but testing event listeners is tricky. You could mock locally the function on of mockStreamingPlugin so you don't have to check for the second arg of the first call like this

```ts
let cb: (({streams}) => void;

mockStreamingPlugin.on.mockImplementation((event, callback) =>  {
   if (event ===  "pc:track:remote") {
      cb = callback
   }
}
```

That would be a bit easier to understand imo because I'm not sure it's clear for everyone what `mockStreamingPlugin.on.mock.calls[0][1]` represents.

Also if this hook is used at a single place in the code I'd try to see if I can test it through an integration of a component test rather than through a hook test. I usually don't recommend testing hooks unless they're highly generic because they're extremely coupled to implementation details, like almost any refactor on it will break tests and sometimes make the test completely obsolete.

Hope this helps, let me know if you find anything!

**Comment by OlliePugh** [comment] 2023-10-12 16:50
Thanks for the reponse, this superrrr strange, when I run in debug mode and go step by step, I see the setState get called before the expect is called, not sure why that isn't being picked up. even when I put some log statements in they also back up this theory.

Test Code
```typescript
const mockTrack = jest.fn();

    const { result, rerender } = renderHook(() =>
      useJanus({
        url: "ws://example.com/janus",
        connectionOptions: { keepalive: true },
        streamId: 123,
      })
    );

    await act(async () => {
      await result.current.watch();

      expect(mockStreamingPlugin.on).toHaveBeenCalledWith(
        "pc:track:remote",
        expect.any(Function)
      );
      mockStreamingPlugin.on.mock.calls;
      const onMethod = mockStreamingPlugin.on.mock.calls[0][1];

      onMethod({ streams: [mockTrack] });
    });
    console.log("before rerender");
    rerender(null);
    console.log("after rerender");
    expect(result.current.remoteStream).toBe(mockTrack);
```

Source code
```typescript
streamingPlugin.on("pc:track:remote", (trackEvent: RTCTrackEvent) => {
      if (remoteStream == null) {
        console.log("setting remote stream");
        setRemoteStream(trackEvent.streams[0]);
      }
    });
```

This is strange as IMO this should be passing. I don't think I know enough about react lifecycles to try and dig deeper, but if I find some time I can try and take a look.

**Comment by pierrezimmermannbam** [comment] 2023-10-13 10:26
Interesting, if you move the ` expect(result.current.remoteStream).toBe(mockTrack);` before the `rerender(null)` does it work? Maybe the `stop` function is called at some point somehow? What is the output if you log `remoteStream` in the hook?

**Comment by pierrezimmermannbam** [comment] 2023-10-25 09:12
I cannot see what's going wrong here, if it does call ` setRemoteStream(trackEvent.streams[0]);` and `trackEvent.streams[0]` I don't see what could go wrong. If you can provide a reproduction repo I might be able to help but for now I don't see how I could be of any assistance

**Comment by mdjastrzebski** [comment] 2023-10-25 17:05
@OlliePugh I agree with @pierrezimmermannbam we would need a minimal repo that showcases to error. The current repro code snippet relies on many functions from your project and 3rd party dependencies. The issue observed by you might easily be coming from one of these. By producing a minimal repo we can verify if the issue is indeed in RNTL and use it as a base of unit tests to make sure that code changes we make resolve the issue.

**Comment by OlliePugh** [comment] 2023-10-29 19:35
Yeah sorry I realise its an impossible task for you guys to try and work out whats going on when I am not giving too much info!

I have made a branch that contains the issue and the commands I am using to see the issue.

https://github.com/OlliePugh/issues/tree/react-native-testing-1511

Let me know if there is anything else I need to provide to try and work out what is going on.

**Comment by pierrezimmermannbam** [comment] 2023-11-06 17:44
Hello @OlliePugh, I found the problem in your test! The issue is that you call `setRemoteStream` with a function (mockTrack is a jest.fn) that returns undefined. What happens is that react sets the state with the return value and so remoteStream is set to undefined.

```tsx
// This is basically what happens, this sets the state to undefined
setState(() => undefined)

// This would set the state to mockTrack
setState(() => mockTrack) 
``` 

It looks like there is no reason for mockTrack to be a jest.fn so you can replace it with an empty object for instance or a mock of a `MediaStream` and your test will work

**Comment by OlliePugh** [comment] 2023-11-07 08:37
Ahh!! Thank you so much!! I never knew jest.fn() would be considered null when used in a function/expect.

Do you have a buymeacofeee or something similar??

**Comment by pierrezimmermannbam** [comment] 2023-11-07 08:49
It's not considered null in expect but if no implementation is provided it's implem is equivalent to `() => undefined` and `setState(() => undefined)` will set the state to undefined. 

No I don't have one but I appreciate you asking, I'm glad if I could help you

I'll close this issue then since it's not related to RNTL

**Closed by pierrezimmermannbam** 2023-11-07 08:49 UTC

**Comment by OlliePugh** [comment] 2023-11-07 09:23
Ahhh I forgot that you can use a callback in setState setters! Thanks for the explanation!
