### ISSUE TITLE
Test render in ReactNative with Jest and reactnative-testing-library: You are trying to `import` a file after the Jest environment has been torn down

### ISSUE THREAD

**Issue by FraBzz** [callstack/react-native-testing-library#860] opened 2021-11-10 10:07 UTC
I have a problem when I try to test render method in my ReactNative application with EXPO, I am using JEST and reactnative-testing-library. This is my code:

```
import { render, fireEvent, cleanup, wait } from '@testing-library/react-native';
import { LoginScreen } from '../../App/screens/LoginScreen';    
import '@testing-library/jest-native/extend-expect';    
import { View } from "react-native";        
    
const fakeNavigation = {    
    navigation: {} as any    
}        
    
it("renders correctly", () => {    
  const screen =  render(<LoginScreen {...fakeNavigation}>{() => <View />}</LoginScreen>);});
```

Before writing this question I watched this link Reference error: `import` a file after the Jest environment has been torn down and also tried workaround

`jest.useFakeTimers()`

but nothing works. As suggested in comment, I attached LoginScreen code's component

```
import React, { Component, Fragment, useContext } from "react";
import {
  TouchableOpacity,
  Dimensions,
  Text,
  Image,
  View,
  StyleSheet,
  ScrollView,
  Platform,
} from "react-native";

import { Formik } from "formik";
import * as Yup from "yup";

import CustomIcon from "../icon-font";
import Fonts from "../constants/Fonts";
import Colors from "../constants/Colors";

import LoginForm from "../forms/LoginForm";
import { UserContext } from "../contexts/UserContext";

type LoginScreenProps = {
  navigation: any;
};

const LoginScreen: React.FC<LoginScreenProps> = (props) => {
  const { _fetchLogin, logOut, user } = useContext(UserContext);

  const loginSchema = Yup.object().shape({
    username: Yup.string().email().required("Please enter a correct email"),
    password: Yup.string().required("Please enter a correct password"),
  });

  let handleLogOut = (user: any) => {
    logOut(user);
    props.navigation.goBack();
  };

  return (
    <ScrollView
      style={{
        flex: 1,
        backgroundColor: Colors.primaryDark,
      }}
    >
      <View>
        <TouchableOpacity
          style={{
            marginTop: Platform.OS === "ios" ? 52 : 32,
            marginLeft: 16,
            zIndex: 5,
            position: "relative",
          }}
          onPress={() => props.navigation.goBack()}
        >
          <View>
            <CustomIcon
              name="angle-left"
              size={32}
              color="white"
              style={{
                width: 48,
                height: 48,
                backgroundColor: "transparent",
              }}
            />
          </View>
        </TouchableOpacity>

        <View
          style={{
            justifyContent: "center",
            alignItems: "center",
            zIndex: 1,
            position: "relative",
          }}
        >
          <Image
            style={{
              width: 150,
              height: 150,
              marginTop: -72,
              marginBottom: 48,
              zIndex: 1,
            }}
            source={require("../../assets/images/logSignIn.png")}
          />
          <View
            style={{
              width: 300,
              height: 300,
              borderColor: Colors.white,
              borderWidth: 1,
              borderRadius: 300,
              zIndex: 1,
              position: "absolute",
              top: -150,
              opacity: 0.1,
            }}
          />
          <View
            style={{
              width: 500,
              height: 500,
              borderColor: Colors.white,
              borderWidth: 1,
              borderRadius: 600,
              zIndex: 1,
              position: "absolute",
              top: -250,
              opacity: 0.1,
            }}
          />
          {!user.logged ? (
            <View style={{ paddingBottom: 600, zIndex: 2 }}>
              <Formik
                validationSchema={loginSchema}
                initialValues={{
                  username: "",
                  password: "",
                }}
                onSubmit={async (values, actions) => {
                  await _fetchLogin(values);
                  actions.setSubmitting(false);
                }}
              >
                <LoginForm {...props} />
              </Formik>
            </View>
          ) : (
            <View
              style={{
                width: 500,
                height: 500,
              }}
            >
              <Image
                style={{
                  width: 500,
                  height: 500,
                  top: -100,
                  left: -5,
                  position: "absolute",
                  zIndex: -3,
                }}
                source={require("../../assets/images/signUp.gif")}
              />
              <TouchableOpacity
                style={{
                  alignItems: "center",
                  zIndex: 2,
                  position: "relative",
                }}
                onPress={() => props.navigation.navigate("HomeNavigator")}
              >
                <View style={styles.submit}>
                  <Text style={styles.textInfo}> Go to homepage </Text>
                </View>
              </TouchableOpacity>
            </View>
          )}
        </View>
      </View>
    </ScrollView>
  );
};

export default LoginScreen;

const styles = StyleSheet.create({
  submit: {
    borderRadius: 32,
    padding: 16,
    backgroundColor: Colors.tertiary,
    flexDirection: "row",
    alignSelf: "center",
    marginTop: 184,
    paddingLeft: 32,
    paddingRight: 32,
    height: 48,
  },

  textInfo: {
    fontSize: 16,
    fontFamily: Fonts.primary,
    color: Colors.white,
  },
});
```

**Comment by AugustinLF** [comment] 2022-03-28 16:09
Without a repo for us to repro it is very hard to figure out what's happening (I've tried reproducing it by removing all the external dependencies of your snippet, but of course the test passed). The few times I got this error was because of async `import`, is it something that you have in your app? If that's not the case, something `async` is happening in your app when you're rendering this component, and since it's not shown in the example you sent, I'm not sure we can help you.

I'll close the issue considering that it's not actionable, but please come back with a way for me to reproduce the issue and I'll see if the problem is on our end (or suggest a solution on your end)

**Closed by AugustinLF** 2022-03-28 16:09 UTC
Labels: question
