### ISSUE TITLE
V7 getByText no longer find translation string

### ISSUE THREAD

**Issue by dephiros** [callstack/react-native-testing-library#553] opened 2020-09-25 22:15 UTC
## Describe the bug
In our codebase, we implement translation with jsLingui and have code like this:
```js
// trivial implementation of Trans

const Trans = (message) => message;

const Component = () => (
    <Text>
      <Trans>There was a problem fetching data.</Trans>
    </Text>
)
```
`Trans` would render a string.
Previously, `getByText("There was a problem fetching data.")` would return a match and it no longer does

## Expected behavior
`getByText("There was a problem fetching data.")` should return a match

## Steps to Reproduce

See above

## Screenshots

debug() would render
```
        <Text>
          There was a problem fetching data.
        </Text>
```

## Versions

```
  npmPackages:
    @testing-library/react-native: ^7.0.2 => 7.0.2
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-test-renderer: 16.11.0 => 16.11.0
```

**Comment by thymikee** [comment] 2020-09-28 13:54
This should definitely pass. cc @AugustinLF working on this field

**Comment by AugustinLF** [comment] 2020-09-29 15:19
Yep, there's some changes incoming to the way we find text in the rendered component. This use case _should_ be covered, I also feel that it was already covered. Would you mind having a look at #554 and see if it works for your use case?

**Comment by dephiros** [comment] 2020-09-29 16:07
> Yep, there's some changes incoming to the way we find text in the rendered component. This use case _should_ be covered, I also feel that it was already covered. Would you mind having a look at #554 and see if it works for your use case?

@AugustinLF , thanks for the response. I will try today and report back

**Comment by jbolotin** [comment] 2020-10-28 02:29
Experiencing this as well with react-intl

**Comment by dattarzadeh-evidation** [comment] 2020-10-30 01:02
We are possibly experiencing this as well. We are using `i18n-js` and `expo-localization`. We are on `react-native` v0.63.3.

**Comment by vcarl** [comment] 2021-05-06 15:18
Also experiencing this with Lingui, I've set up [a reproduction](https://github.com/vcarl/rtl-lingui-repro) of the issue.

**Comment by nirbenya** [comment] 2021-05-23 03:16
I'v found a workaround for react-intl.
When you test your component with RTL you probably wrap your component with an intl-provider.
Something like that:

```
const { getByText } = render(<IntlProvider><MyComponent /> </IntlProvider>
```
So what fixes the issue for me and allowing me to use getByText is turning this to:

```import { Text } from 'react-native';

const { getByText } = render(<IntlProvider textComponent={Text}><MyComponent /> </IntlProvider>
```
This forces the FormattedMessage component to use Text as a wrapper instead of React.Fragment which is the default.

**Comment by thymikee** [comment] 2021-05-23 10:33
@nirbenya thanks for sharing! This makes sense, because RNTL uses native `Text` for matching text nodes.

**Comment by jehartzog** [comment] 2021-07-17 20:19
We are using `i18n-js` and are seeing this too. I ended up with a [patch-package](@testing-library+react-native+7.2.0.patch) which fixes it, although you end up with duplicate nodes matching. Doesn't really matter for our current use case, I end up just matching text via:
```ts
expect(queryAllByText(/look for me/i).length).toBeGreaterThanOrEqual(1);
```

**Comment by AugustinLF** [comment] 2022-03-29 10:07
The issue is also related to #937. We're discussing potential solutions there and will therefore close this issue meanwhile. If you disagree with me, please let me know :)

**Closed by AugustinLF** 2022-03-29 10:07 UTC
Labels: bug, duplicate
