### ISSUE TITLE
Wrapped TextInput with editable set to false calls onFocus anyway

### ISSUE THREAD

**Issue by TMaszko** [callstack/react-native-testing-library#1384] opened 2023-04-12 20:28 UTC
## Describe the bug
When `fireEvent` is called with wrapped TextInput(i.e with `styled-components`) that is disabled the event bubbles up.
For example: We want to check if the `TextInput` component is actually disabled we might check whether `onFocus` event handler was called or not.

## Expected behaviour
`onFocus` handler should not be called if the `TextInput` is disabled (aka `editable` prop set to `false`)

## Steps to Reproduce
https://github.com/TMaszko/FireEventBug
Install dependencies and run `yarn test`

## Versions

 npmPackages:
    @testing-library/react-native: ^12.0.1 => 12.0.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-test-renderer: ^18.2.0 => 18.2.0

**Comment by pierrezimmermannbam** [comment] 2023-04-13 11:40
Hello @TMaszko, this happens because the component that wraps the TextInput also has an onFocus prop and since it's not a TextInput from React Native the check on enabled prop is not done. This issue is a duplicate of #1261 so I think we can close this one and continue the discussion on the other issue

**Comment by TMaszko** [comment] 2023-04-13 12:07
I know that but touch responder will have this prop so we can do the additional check like I did in #1385

**Comment by mdjastrzebski** [comment] 2023-04-24 06:16
Duplicate of #1261

**Closed by mdjastrzebski** 2023-04-24 06:16 UTC

**Comment by mdjastrzebski** [comment] 2023-05-04 10:14
This issue has been resolved in [v12.1.2](https://github.com/callstack/react-native-testing-library/releases/tag/v12.1.2) 🚀
