### ISSUE TITLE
Update ByRole queries to only accept roles

### ISSUE THREAD

**Issue by pierrezimmermannbam** [callstack/react-native-testing-library#1527] opened 2023-11-14 09:36 UTC
## Describe the Feature

In short, I want type the role as `Role` instead of `string | Regexp`

When using `byRole` queries, the role is typed as `string | Regexp`. What's the most problematic imo is to not have any autocompletion. It takes more time but mostly it can result in tests failing because of a misspell. This could be solved by using the same trick we use for `fireEvent` and we could keep the same type. However I don't think any string should be allowed but only valid roles. Also I don't see valid use cases for using regexp with role queries so I don't think it should be allowed. I don't know why it's supported though so I may be missing valid use cases.  
What are your thoughts on this @mdjastrzebski @MattAgn ?

**Comment by mdjastrzebski** [comment] 2023-11-14 10:40
That seems like a good idea 🌟. We should guide the user towards proper roles. 

Some points to consider:
1. [RTL](https://testing-library.com/docs/queries/byrole/) seems to accept `string`, so we would introduce small discrepancy - I'm not too worried about it.
2. Such change would be a breaking change, so we need to put it on hold it for v13. 
3. Perhaps for the current major version we could print a deprecation/warning if user queries with Regex or string that is not a valid role.
4. Remember there are two types of roles, classing `AccessibilityRole` and aria `Role`. Both are supported but they have different values sometimes, we need to support both.

@pierrezimmermannbam feel free to proceed with point 3 if you have some capacity.

**Comment by pierrezimmermannbam** [comment] 2023-11-14 13:01
The thing is I'm not sure we could verify if it's a valid role. For that we'd need an array with the roles but RN only exports the type afaik and we can't do runtime validation based on a type. We could however add autocompletion for valid roles before the next major but it would mean some rework. We may need to figure out first when we want to release v13 to see if it's worth it

**Comment by MattAgn** [comment] 2023-11-14 15:51
I agree with the idea of stronger types. 
@pierrezimmermannbam you mentioned checking roles a runtime, but isn't type checking enough of a safety net?

**Comment by pierrezimmermannbam** [comment] 2023-11-14 16:18
@MattAgn it is, I was referring to what @mdjastrzebski was suggesting, that we could issue warnings before publishing the next major

**Comment by mdjastrzebski** [comment] 2023-11-14 16:47
@pierrezimmermannbam , @MattAgn: Types vs runtime dichotomy is real, I've browser RN source but they do not seem to export runtime values for allow functions.

My idea about detecting it at runtime was intended for v12 improvement until we are ready to ship v13 with changes types which would be a breaking change.
If that is not easily achievable, let's wait with typing change till v13.

**Comment by MattAgn** [comment] 2023-11-20 08:43
I agree with you, and I don't think many users use roles that are neither `AccessibilityRole` and `aria Role`. And if they do, I guess it should not be too hard to fix their tests to fit the new typing

**Comment by mdjastrzebski** [comment] 2024-03-12 09:01
@pierrezimmermannbam @MattAgn reviving this old improvement idea. What about doing [TS hack](https://github.com/callstack/react-native-testing-library/blob/4e148bdb0573fcb86686482c3af1d1e02e1cc937/src/fire-event.ts#L109) on suggesting the proper roles for v12, and then potentially restricting it for v13?

**Comment by mdjastrzebski** [comment] 2024-04-29 20:32
Merged #1596 with autocomplete.

**Closed** 2024-08-24 09:32 UTC
