### ISSUE TITLE
UNSAFE_queryAllByType not finding custom components

### ISSUE THREAD

**Issue by temharay** [callstack/react-native-testing-library#548] opened 2020-09-18 00:52 UTC
Not sure if it is a bug but here goes. My custom component is:

```
const DV = (props) =>{
const { name } = props;
 return (<Text>{name}</Text>)
}

```
now I use the component in my main component over a loop. but during testing it fails. I simply want to count the total number of DV components:
        
```
          const members = [{'name':'Hellen'},{'name':'Daniels'}];
         const { UNSAFE_queryAllByType } = render(<ScreenPage members={members}/>);
         const DVElements = UNSAFE_queryAllByType(DV);  
         expect(DVElements).toHaveLength(2);

```
it fails with No Instance found error but if i do

```
          const members = [{'name':'Hellen'},{'name':'Daniels'}];
         const { UNSAFE_queryAllByType } = render(<ScreenPage members={members}/>);
         const DVElements = UNSAFE_queryAllByType(Text);  
         expect(DVElements).toHaveLength(2);

```

it passes well. ANything I am missing?

**Comment by AugustinLF** [comment] 2022-03-28 16:35
(probably not relevant anymore considering that the issue is old, but let's try to solve instead of silently closing).

Could you show the implementation of `ScreenPage`? Because if I do something like that both of your tests pass:
```
const ScreenPage = ({ members }) => {
  return (
    <>
      {members.map((member) => (
        <DV key={member.name} name={member.name} />
      ))}
    </>
  );
};
```

**Comment by mdjastrzebski** [comment] 2022-08-03 15:20
Closing issue as stale.

@temharay please report a new GH issue if the problem is present in the current version of RNTL (v11) in recommended setup as in [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic). If so, please also provide a repro repository.

**Closed by mdjastrzebski** 2022-08-03 15:20 UTC
Labels: question, needs repro
