### ISSUE TITLE
Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by seyaobey-dev** [callstack/react-native-testing-library#783] opened 2021-07-16 19:21 UTC
Apologies if this is not the right place, I'm having issues running unit tests with react native expo. I'm getting this error when I run my test  (jest, jest-expo, testing-library/react-native) and I don't know  :
```javascript
    TypeError: Cannot read property 'default' of undefined
      at _default (node_modules/@expo/vector-icons/src/createIconSet.tsx:110:28)
      at Object.<anonymous> (node_modules/@expo/vector-icons/src/AntDesign.ts:5:16)
      at Object.<anonymous> (node_modules/@expo/vector-icons/src/Icons.ts:1:1)
```
The error seems to come from `expo vector icons`. I believe I have correctly setup my tests:

1. jest.config.js
```javascript
module.exports = {
    preset: 'jest-expo',
    setupFilesAfterEnv: ['<rootDir>/setupTest.ts'],
    transformIgnorePatterns: [
        'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)',
    ],
    moduleDirectories: ['node_modules', 'src/testing-setup', '__dirname'],
};
```
2. setupTest.ts
```javascript
import '@testing-library/jest-native/extend-expect';
jest.useFakeTimers('modern');
```
3. test:
```javascript
describe('PageTest01', () => {
    test('it should render', () => {
        const { getByTestId } = render(<PageTest01 />);
        expect(getByTestId('page')).toBeDefined();
    });
});
```
The component under test does not even contain any icon

**Comment by thymikee** [comment] 2021-07-18 10:46
Duplicate of https://github.com/callstack/react-native-testing-library/issues/782. Please ask on Expo/Jest help forums. This is not a help forum and your error is not related to this library.

**Closed by thymikee** 2021-07-18 10:46 UTC
Labels: question
