### ISSUE TITLE
Vitest support

### ISSUE THREAD

**Issue by camilossantos2809** [callstack/react-native-testing-library#1586] opened 2024-04-15 11:24 UTC
## Ask your Question

Is this library supposed to work with vitest?
I'm thinking to migrate from jest but exactly in `.tsx` files where my tests are slow, I'm getting some errors:
```
SyntaxError: Cannot use import statement outside a module
 ❯ Object.<anonymous> node_modules/@testing-library/react-native/src/helpers/format-default.ts:1:1
```

```
// vite.config.ts
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    globals: true,
    setupFiles: "./src/utils/test-helpers/setup-vitest.ts",
    server: {
      deps: {
        inline: ["react-native"],
      },
    },
  },
});
```

```
// setup-vitest.ts
import "@testing-library/react-native/extend-expect";
```

Without setup file it gives a different error:

```
SyntaxError: Cannot use import statement outside a module
 ❯ Object.<anonymous> node_modules/@testing-library/react-native/src/helpers/host-component-names.tsx:3:1
```

**Comment by pierrezimmermannbam** [comment] 2024-04-18 16:10
The issue is that the RN ecosystem as a whole doesn't support vitest for now and since testing in RN environment requires a lot of mock, most RN librairies have a jest preset and not a vitest preset. For instance RN has a jest preset but not a vitest preset. Maybe it could work if you alias vitest globals to match the ones of jest but I haven't tried it. It would probably not be very hard for RNTL to support vitest but it would only make sense if it was supported more widely through the RN ecosystem

**Comment by mdjastrzebski** [comment] 2024-04-18 18:50
A project to watch then, and potentially collaborate in the future is [VXRN](https://vxrn.dev) who work on bringing Vite into RN world. It's in alpha now but seems to be run by smart folks.

**Comment by mdjastrzebski** [comment] 2024-04-18 20:23
Closing as not fixable for now.

**Closed** 2024-04-18 20:23 UTC
Labels: question
