### ISSUE TITLE
"Cannot read property 'testID' of null"

### ISSUE THREAD

**Issue by milesj** [callstack/react-native-testing-library#785] opened 2021-07-19 22:26 UTC
## Describe the bug

Currently in the process of upgrading RN to v0.64 and RNTL to v8-rc.0. After upgrading RNTL, many tests started throwing errors similar to the following:

```
TypeError: Cannot read property 'testID' of null
--
  |  
  | at getNodeByTestId (node_modules/@testing-library/react-native/build/helpers/byTestId.js:11:61)
  | at node_modules/@testing-library/react-native/build/helpers/byTestId.js:15:44
```

```
TypeError: Cannot read property 'testID' of nullError: Cannot read property 'testID' of null
--
  |  
  | 83 \|   delayed = false,
  | 84 \| ) => {
  | > 85 \|   await waitFor(async () => {
  | \|         ^
  | 86 \|     await cb();
  | 87 \|
  | 88 \|     // Ensure an additional tick has fired, otherwise the act would close before
  |  
  | at _callee4$ (src/support/testHelpers.tsx:85:9)
```

```
TypeError: Cannot read property 'testID' of nullError: Cannot read property 'testID' of null
--
  |  
  | 571 \|
  | 572 \|       it('renders the preview button', async () => {
  | > 573 \|         await waitFor(() => renderResult.queryByTestId('PreviewButton'));
  | \|               ^
  | 574 \|         expect(renderResult.queryByTestId('PreviewButton')).toBeTruthy();
  | 575 \|       });
  | 576 \|
```

## Expected behavior

It doesn't throw.

## Steps to Reproduce

Honestly, I have no idea why this is happening (all the tests look correct), or if the RNTL upgrade is the cause.

But I figured I would report this issue in case others are running into the same problem.

## Versions

```
  npmPackages:
    @testing-library/react-native: 8.0.0-rc.1 => 8.0.0-rc.1
    react: 17.0.2 => 17.0.2
    react-native: 0.64.2 => 0.64.2
    react-test-renderer: 17.0.2 => 17.0.2
```

**Comment by tbezman** [comment] 2021-07-21 18:18
I setup a minimum reproduction repo for this. You can see the test [here](https://github.com/tbezman/testing-library-null-bug/blob/master/__tests__/App-test.tsx). It looks like the problem only occurs when one of the components suspend.

The above reproduction is based off this command `npx react-native init AwesomeTSProject --template react-native-template-typescript`

**Comment by milesj** [comment] 2021-07-21 18:43
We currently patched the lib to unblock us.

```diff
diff --git a/node_modules/@testing-library/react-native/build/helpers/byTestId.js b/node_modules/@testing-library/react-native/build/helpers/byTestId.js
index b58543f..f7c792a 100644
--- a/node_modules/@testing-library/react-native/build/helpers/byTestId.js
+++ b/node_modules/@testing-library/react-native/build/helpers/byTestId.js
@@ -8,6 +8,10 @@ exports.queryByTestId = exports.queryAllByTestId = exports.getByTestId = exports
 var _makeQueries = require("./makeQueries");
 
 const getNodeByTestId = (node, testID) => {
+  if (!node.props) {
+    return false
+  }
+
   return typeof testID === 'string' ? testID === node.props.testID : testID.test(node.props.testID);
 };
```

**Comment by conor909** [comment] 2021-07-23 09:53
Would this be related to my question? https://github.com/callstack/react-native-testing-library/issues/786

**Comment by Aleksefo** [comment] 2021-08-13 19:22
Happens on version 7.1.0+ Downgrading to version 7.0.2 fixes the issue.

    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-redux": "^7.2.0",
    "redux-actions": "^2.6.5"
    "@testing-library/jest-native": "^4.0.2",
    "@testing-library/react-native": "7.0.2",
    "jest": "^26.6.3",
    "react-test-renderer": "17.0.1",
    "redux-mock-store": "^1.5.4",

**Comment by getsaf** [comment] 2021-12-15 23:27
In our case, it turns out the culprit was a suspense fallback being set to null:

```ts
<Suspense fallback={null}>
  <SomethingThatSuspends />
</Suspense>
```

The types for react allow `null` values, so I think this a legitimate bug.

**Comment by jasperkuperus** [comment] 2022-01-26 07:24
I ran into this same issue for a different reason:

```
    const { getByText, getByTestId } = render(
      <RawIntlProvider value={getIntl()}>
        <MyComponent />
      ,
      </RawIntlProvider>,
    );
```

Where `RawIntlProvider` come from `react-intl`.

Watch the weirdly places comma before `</RawIntlProvider>`. Somehow, `prettier` managed to format my JSX in that style, which didn't break the whole test, but just gave me the `Cannot read property 'testID' of null` error. Removing that comma, properly closing all tags fixed this issue for me.

**Comment by mdjastrzebski** [comment] 2022-08-03 15:18
According to `ReactTestInstance` TS typing `props` should not be nullish. I think we could add some check in the code to support this case.

**Closed** 2022-09-30 11:44 UTC
Labels: bug
